### ISSUE TITLE
job apply issues

### ISSUE THREAD

**Issue by Mhalat1** [IggsGrey/linkedin-easy-apply-bot#12] opened 2024-08-04 10:27 UTC
i have this error

PS C:\Users\me\OneDrive\Desktop\linkedin-easy-apply-bot-main> npm run apply

> scripts@1.0.0 apply
> ts-node ./scripts/apply.ts SUBMIT

> [8/4/2024, 12:25:08] Logged in to LinkedIn
press enter to pause the program
TimeoutError: Waiting for selector `.jobs-search-results-list li.jobs-search-results__list-item:nth-child(7)` failed: Waiting failed: 5000ms exceeded
    at Timeout.<anonymous> (C:\Users\me\OneDrive\Desktop\linkedin-easy-apply-bot-main\node_modules\puppeteer-core\src\common\WaitTask.ts:79:11)
    at listOnTimeout (node:internal/timers:573:17)
    at processTimers (node:internal/timers:514:7)

**Comment by IggsGrey** [comment] 2024-08-04 10:34
Thanks for opening this issue @Mhalat1 .

There's been two other reports on this already, the problem is that I can't seem to reproduce it myself (it works for me unfortunately :) ).

Will keep trying regardless

**Comment by Mhalat1** [comment] 2024-08-06 09:52
Also i have this issue before that
i just replaced createIncognitoBrowserContext by createBrowserContext 
maybe it's reason but i dont see any correlations

           ^
TSError: ⨯ Unable to compile TypeScript:
scripts/apply.ts:39:33 - error TS2551: Property 'createIncognitoBrowserContext' does not exist on type 'Browser'. Did you mean 'createBrowserContext'?

39   const context = await browser.createIncognitoBrowserContext();
                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  node_modules/puppeteer/lib/types.d.ts:241:14
    241     abstract createBrowserContext(options?: BrowserContextOptions): Promise<BrowserContext>;
                     ~~~~~~~~~~~~~~~~~~~~
    'createBrowserContext' is declared here.
scripts/apply.ts:75:11 - error TS18047: 'applicationPage' is possibly 'null'.

75     await applicationPage.bringToFront();
             ~~~~~~~~~~~~~~~
scripts/apply.ts:92:9 - error TS2322: Type 'Page | null' is not assignable to type 'Page'.
  Type 'null' is not assignable to type 'Page'.

92         page: applicationPage,
           ~~~~

  apply/index.ts:30:3
    30   page: Page;

**Comment by IggsGrey** [comment] 2024-08-06 13:38
So I let the program run till the end and I encountered this error message after a while

>  TimeoutError: Waiting for selector .jobs-search-results-list li.jobs-search-results__list-item:nth-child(7) failed: Waiting failed: 5000ms exceeded


So I paused the program at that point and reviewed my logs, and this is is what I see in my console logs and on the program screen


```
> scripts@1.0.0 apply
> ts-node ./scripts/apply.ts SUBMIT

[8/6/2024, 13:27:31] Logged in to LinkedIn
press enter to pause the program
[8/6/2024, 13:28:01] Error: Submit button not found
[8/6/2024, 13:28:01] Error applying to Frontend Developer
Frontend Developer at Unknown
[8/6/2024, 13:28:15] Error: Submit button not found
[8/6/2024, 13:28:15] Error applying to Senior Full Stack Developer
Senior Full Stack Developer at Unknown
[8/6/2024, 13:28:29] Error: Submit button not found
[8/6/2024, 13:28:29] Error applying to Senior Front-end React Engineer
Senior Front-end React Engineer with verification at Unknown
[8/6/2024, 13:28:53] Error: Submit button not found
[8/6/2024, 13:28:53] Error applying to Senior React Native Developer
Senior React Native Developer with verification at Unknown
error that occured TimeoutError: Waiting for selector `.jobs-search-results-list li.jobs-search-results__list-item:nth-child(7)` failed: Waiting failed: 5000ms exceeded
    at Timeout.<anonymous> (/REDACTED/linkedin-easy-apply-bot/node_modules/puppeteer-core/src/common/WaitTask.ts:79:11)
    at listOnTimeout (node:internal/timers:573:17)
    at processTimers (node:internal/timers:514:7)
```


At the same time here is the state of the program at the time of this log

<img width="805" alt="Screenshot 2024-08-06 at 1 36 47 PM" src="https://github.com/user-attachments/assets/c3978b1f-84b4-4566-a076-6ae301fac961">


I'm going to infer that the search filters you are using are yielding 0 results but the program is not handling this scenario properly

**Comment by IggsGrey** [comment] 2024-08-12 21:59
Will be closing this as "completed" in a few more days if no one has any other issues related to this.

**Closed as completed** 2024-09-03 14:47 UTC

**Comment by SiddharthBhawsar** [comment] 2024-12-03 08:00
@IggsGrey 
I am still getting the same error even though for me the jobs are visible 

```
TimeoutError: Waiting for selector `.jobs-search-results-list li.jobs-search-results__list-item:nth-child(7)` failed: Waiting failed: 5000ms exceeded
    at Timeout.<anonymous> (/Users/u1536988/Downloads/linkedin-easy-apply-bot-main 2/node_modules/puppeteer-core/src/common/WaitTask.ts:79:11)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
```

![image](https://github.com/user-attachments/assets/ea659733-ae2b-4221-b650-d61cea9965a6)

**Comment by IggsGrey** [comment] 2024-12-03 10:46
@SiddharthBhawsar was the script able to apply to any jobs at all or does this happen immediately the page in the attached image is open?

**Comment by SiddharthBhawsar** [comment] 2024-12-03 11:09
@IggsGrey it just opens this page and halts, not even one successfully applied job. I am using your updated main branch btw.

**Comment by IggsGrey** [comment] 2024-12-03 11:52
Just checked it out @SiddharthBhawsar this looks like a different issue. Linkedin has updated their selectors. Created a new issue for this -> https://github.com/IggsGrey/linkedin-easy-apply-bot/issues/15
